/**
 * Example solidity-docgen configuration file
 *
 * Copy this to docgen.config.ts and customize for your project.
 */

import type { DocgenConfig } from "./src/config/schema";

const config = {
  // Root directory of your Solidity project
  rootDir: process.cwd(),

  // Location of compiled build info artifacts
  // Typically generated by Hardhat or Truffle
  buildInfoDir: "artifacts/build-info",

  // Output directory for generated markdown files
  outDir: "docs",

  // Directory containing custom Handlebars templates
  // Optional: if omitted, uses built-in templates
  templateDir: "templates",

  // Exclude contracts by source path pattern
  // Supports glob patterns: *, ?, **
  exclude: [
    "**/Mock*.sol", // Mock contracts
    "**/test/**", // Test contracts
    "**/deprecated/**", // Deprecated contracts
  ],

  // Only include contracts of these kinds
  // Valid values: "contract", "interface", "library", "abstract", "source"
  contractKinds: ["contract", "interface", "library"],

  // Custom properties to extract from docstrings
  // Use @custom:propertyName in your Solidity comments
  customProperties: {
    category: (doc) => {
      // Auto-categorize contracts
      if (doc.contractName.includes("ERC")) return "standards";
      if (doc.contractName.includes("Factory")) return "factories";
      if (doc.contractKind === "library") return "libraries";
      return "contracts";
    },

    security: (doc) => {
      // Extract @custom:security tag from docstring
      if (doc.notice && doc.notice.includes("@custom:security")) {
        const match = doc.notice.match(/@custom:security\s+([^\n]+)/);
        return match ? match[1] : undefined;
      }
      return undefined;
    },

    gasEstimate: (doc) => {
      // Extract gas cost estimates
      if (doc.notice && doc.notice.includes("@custom:gasEstimate")) {
        const match = doc.notice.match(/@custom:gasEstimate\s+([^\n]+)/);
        return match ? match[1] : undefined;
      }
      return undefined;
    },
  },

  // UI Plugins for extending behavior
  plugins: [
    {
      name: "example-plugin",
      hooks: {
        // Runs for each parsed contract
        onItem: async (item, context) => {
          // Example: Add custom properties to each contract
          return {
            ...item,
            category: item.category || "general",
          };
        },

        // Runs on filtered items before rendering
        onFilter: async (items, context) => {
          // Example: Sort by contract name
          return items.sort((a, b) =>
            a.doc.contractName.localeCompare(b.doc.contractName),
          );
        },

        // Runs on rendered files before writing
        onWrite: async (files, context) => {
          // Example: Add header comment to every file
          return files.map((f) => ({
            ...f,
            content:
              "<!-- Auto-generated by solidity-docgen v2 -->\n" + f.content,
          }));
        },

        // Runs after all files are written
        onFinish: async (files, context) => {
          console.log(`✅ Generated ${files.length} documentation files`);
        },
      },
    },
  ],

  // Default YAML frontmatter fields
  // These are applied to every generated markdown file.
  // License from SPDX headers in source files will override the default.
  frontmatter: {
    // Site-wide metadata
    description: "API reference for all contracts",
    author: "Your Project",
    repository: "https://github.com/your-org/your-repo",

    // Default license (can be overridden per-contract via SPDX header)
    license: "MIT",

    // Site builder specific
    sidebarLabel: "Contracts",
  },

  // Target static site generator
  // Affects frontmatter format and organization
  // Options: "generic", "vitepress", "nextra", "mkdocs", "jekyll"
  target: "vitepress",

  // Auto-generate VitePress sidebar configuration
  // Set to true to automatically generate .vitepress/config.ts
  generateVitepressSidebar: true,

  // Site title for auto-generated VitePress config
  siteTitle: "Solidity Scale Codec",

  // Site description for auto-generated VitePress config
  siteDescription: "API reference for all contracts",

  // Repository URL for VitePress config
  repository: "https://github.com/your-org/your-repo",
} satisfies DocgenConfig;

export default config;
